-- Product owner request: ROAM becomes a public product where anyone can
-- spin up their own trip from the landing page (app/page.tsx), not just
-- the private Kassandra 2026 pilot. Creation happens server-side only
-- (app/api/trips/create/route.ts, using the service-role key -- same
-- "content changes never go through the anon key" rule as everywhere
-- else, see the initial_schema.sql header), so no new insert policies
-- are needed here.
--
-- Two columns support that flow:
--   created_by_device_id -- lets the creation route enforce "at most one
--     new trip per device per 24h" without a separate rate-limit table.
--     Null for every pre-existing trip (Kassandra), which was seeded, not
--     created through this path.
--   content_status -- a public trip's Discover/Battle content is
--     generated by calling the Claude API after the trip row exists, not
--     in the same instant -- this tracks that: 'pending' right after
--     creation, 'ready' once generation + insertion succeeds, 'failed' if
--     the AI call or the content it returned couldn't be used (the trip
--     still exists, just empty, and the Home page shows this state
--     instead of a broken-looking empty dashboard). Defaults to 'ready'
--     so Kassandra and any other already-seeded trip are unaffected.

alter table trips
  add column created_by_device_id text,
  add column content_status text not null default 'ready'
    check (content_status in ('pending', 'generating', 'ready', 'failed'));

-- Both rate-limit checks in the creation route filter on a recent time
-- window -- global ("any trip created in the last 24h") and per-device.
create index trips_created_at_idx on trips (created_at);
create index trips_created_by_device_id_idx on trips (created_by_device_id, created_at);
