-- ROAM activity schema: rows generated by participants during the pilot.
-- Trust model (no auth): every anonymous device gets a client-generated
-- device_id (src/lib/device.ts). device_id is a client-asserted identifier,
-- not a cryptographic credential -- see docs/DATABASE.md "Security model"
-- for why this tradeoff is acceptable for a private, invite-only pilot.

create table participants (
  id uuid primary key default gen_random_uuid(),
  trip_id uuid not null references trips (id) on delete cascade,
  device_id text not null,
  display_name text not null,
  role text not null check (role in ('adult', 'child')),
  created_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  unique (trip_id, device_id)
);

create index participants_trip_id_idx on participants (trip_id);

create table extra_assignments (
  id uuid primary key default gen_random_uuid(),
  extra_id uuid not null references extras (id) on delete cascade,
  participant_id uuid not null references participants (id) on delete cascade,
  status text not null default 'assigned'
    check (status in ('assigned', 'viewed', 'completed')),
  assigned_at timestamptz not null default now(),
  viewed_at timestamptz,
  unique (extra_id, participant_id)
);

create index extra_assignments_participant_id_idx on extra_assignments (participant_id);

-- Shared by Discover answers and Battle answers, mirroring the merged
-- `questions` table above (kind is inherited via question_id).
create table responses (
  id uuid primary key default gen_random_uuid(),
  question_id uuid not null references questions (id) on delete cascade,
  participant_id uuid not null references participants (id) on delete cascade,
  selected_option_id uuid references answer_options (id) on delete set null,
  response_text text,
  is_correct boolean,
  response_time_ms int,
  created_at timestamptz not null default now(),
  unique (question_id, participant_id)
);

create index responses_participant_id_idx on responses (participant_id);

create table battle_scores (
  id uuid primary key default gen_random_uuid(),
  battle_id uuid not null references battles (id) on delete cascade,
  participant_id uuid references participants (id) on delete cascade,
  team text check (team in ('adults', 'kids')),
  score int not null default 0,
  created_at timestamptz not null default now()
);

create index battle_scores_battle_id_idx on battle_scores (battle_id);

create table feedback (
  id uuid primary key default gen_random_uuid(),
  trip_id uuid not null references trips (id) on delete cascade,
  participant_id uuid references participants (id) on delete set null,
  rating smallint check (rating between 1 and 5),
  comment text,
  created_at timestamptz not null default now()
);

create table analytics_events (
  id uuid primary key default gen_random_uuid(),
  trip_id uuid not null references trips (id) on delete cascade,
  participant_id uuid references participants (id) on delete set null,
  event_name text not null,
  event_props jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index analytics_events_trip_event_idx on analytics_events (trip_id, event_name, created_at);

-- Row Level Security
alter table participants enable row level security;
alter table extra_assignments enable row level security;
alter table responses enable row level security;
alter table battle_scores enable row level security;
alter table feedback enable row level security;
alter table analytics_events enable row level security;

-- participants: readable by everyone (needed for team/leaderboard display
-- names) and writable by anyone, since there is no server-verifiable
-- identity to scope "own row" to. Accepted risk for a private pilot: see
-- docs/DATABASE.md.
create policy "participants are publicly readable" on participants
  for select using (true);
create policy "anyone can join as a participant" on participants
  for insert with check (true);
create policy "anyone can update participant heartbeat/name" on participants
  for update using (true) with check (true);

-- Activity tables: anon can write its own events but cannot read anyone's
-- raw rows back (no select policy = no anon/authenticated select). This
-- stops one device from scraping other participants' answers or scores.
create policy "anyone can record an extra assignment" on extra_assignments
  for insert with check (true);
create policy "anyone can update their assignment status" on extra_assignments
  for update using (true) with check (true);

create policy "anyone can submit a response" on responses
  for insert with check (true);

create policy "anyone can submit a battle score" on battle_scores
  for insert with check (true);

create policy "anyone can submit feedback" on feedback
  for insert with check (true);

create policy "anyone can record an analytics event" on analytics_events
  for insert with check (true);

-- Aggregate-only read path for battle results: exposes team totals without
-- exposing any individual participant's row. SECURITY DEFINER bypasses the
-- (deliberately absent) select policy on battle_scores.
create or replace function public.battle_leaderboard(p_battle_id uuid)
returns table (team text, total_score bigint)
language sql
security definer
set search_path = public
as $$
  select team, coalesce(sum(score), 0) as total_score
  from battle_scores
  where battle_id = p_battle_id and team is not null
  group by team;
$$;

grant execute on function public.battle_leaderboard(uuid) to anon, authenticated;
